config/routes.rb
CredibleDemo::Application.routes.draw do
  resources :orders

  resources :values

  resources :prices

  resources :items do
    collection { post :import }
  end

  root 'orders#new'

end

app/models/value.rb
class Value < ActiveRecord::Base
	has_many :prices
	has_many :items
	belongs_to :order

	accepts_nested_attributes_for :prices, :items
end

app/controllers/values_controller.rb
class ValuesController < ApplicationController
  before_action :set_value, only: [:show, :edit, :update, :destroy]

  # GET /values
  # GET /values.json
  def index
    @values = Value.all
  end

  # GET /values/1
  # GET /values/1.json
  def show
    @value = Value.find(params[:id])
  end

  # GET /values/new
  def new
    @value = Value.new
  end

  # GET /values/1/edit
  def edit
  end

  # POST /values
  # POST /values.json
  def create
    @value = Value.new(value_params)

    respond_to do |format|
      if @value.save
        format.html { redirect_to @value, notice: 'Value was successfully created.' }
        format.json { render action: 'show', status: :created, location: @value }
      else
        format.html { render action: 'new' }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /values/1
  # PATCH/PUT /values/1.json
  def update
    respond_to do |format|
      if @value.update(value_params)
        format.html { redirect_to @value, notice: 'Value was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /values/1
  # DELETE /values/1.json
  def destroy
    @value.destroy
    respond_to do |format|
      format.html { redirect_to values_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_value
      @value = Value.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def value_params
      params[:value]
    end
end

app/helpers/values_helper.rb
module ValuesHelper
end

app/views/values/_form.html.erb
<%= form_for(@value) do |f| %>
  <% if @value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@value.errors.count, "error") %> prohibited this value from being saved:</h2>

      <ul>
      <% @value.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/values/edit.html.erb
<h1>Editing value</h1>

<%= render 'form' %>

<%= link_to 'Show', @value %> |
<%= link_to 'Back', values_path %>

app/views/values/index.html.erb
<h1>Listing values</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @values.each do |value| %>
      <tr>
        <td><%= link_to 'Show', value %></td>
        <td><%= link_to 'Edit', edit_value_path(value) %></td>
        <td><%= link_to 'Destroy', value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Value', new_value_path %>

app/views/values/new.html.erb
<h1>New value</h1>

<%= render 'form' %>

<%= link_to 'Back', values_path %>

app/views/values/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_value_path(@value) %> |
<%= link_to 'Back', values_path %>