config/routes.rb
CredibleDemo::Application.routes.draw do
  resources :orders

  resources :values

  resources :prices

  resources :items do
    collection { post :import }
  end

  root 'orders#new'

end

app/models/order.rb
class Order < ActiveRecord::Base
	has_many :items
	has_many :values
	has_many :prices

	accepts_nested_attributes_for :prices, :values, :items 

	# will help us find the restaurant id and price
	def self.search(order)
		# make sure that order is a string
		order.to_str 
		# this splits our string into separate entries in an array
		list = order.split(/\W+/)
		# this hash will track our restaurant id and price
		specific_order = Hash.new
		# this hash will track our values
		value_tracker = Hash.new
		# iterating over all of the entries in the array
		(0..list.length-1).each do |i| 
			# getting the ids of the entries in order to access other attributes
			ids = Item.where(name: list[i]).ids
			# iterating over potential duplicates of names
			(1..ids.length-1).each do |j|
				# if this is the first entry, making sure to add everything to the hashes
				if i==0
					specific_order = {Item.find_by_id(ids[j]).prices.first.restaurant_id => Item.find_by_id(ids[j]).prices.first.amount}
					unless Item.find_by_id(ids[j]).value_id.nil?
						# if this is part of a value meal
						value_tracker = {Item.find_by_id(ids[j]).value_id => true}
					end
				else
					# after the first entry, should only proceed if we can find key in our hash
					if specific_order.has_key?(Item.find_by_id(ids[j]).prices.first.restaurant_id)
						# taking into account value meals
						unless Item.find_by_id(ids[j]).value_id.nil?
							# adding value meal to our value_track hash
							if value_tracker[Item.find_by_id(ids[j]).value_id].nil?
								tmp_price = (specific_order[Item.find_by_id(ids[j]).prices.first.restaurant_id].to_f + Item.find_by_id(ids[j]).prices.first.amount.to_f)
								specific_order[Item.find_by_id(ids[j]).prices.first.restaurant_id] = tmp_price
								value_tracker = {Item.find_by_id(ids[j]).value_id => true}
							end
							# we don't change price if value meal is already added
						end
						# adding to the price
						tmp_price = (specific_order[Item.find_by_id(ids[j]).prices.first.restaurant_id].to_f + Item.find_by_id(ids[j]).prices.first.amount.to_f)
						# changing price in the hash
						specific_order[Item.find_by_id(ids[j]).prices.first.restaurant_id] = tmp_price
					else 
						# if the order isn't possible
						return "Sorry, you're order isn't possible!"
					end
				end
			end
		end
		# sorting in descending order - want the lowest 
		specific_order.sort_by {|k,v| v}
		# this will be the lowest
		key, value = specific_order.first
		# boom. this is what we want.
		return key, value.to_f()
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @order = Order.new.update_attribute(:name, params[:search])
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  def search
    Order.search(params[:order])
    redirect_to root_url, notice: "This will be the answer."

  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :price)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div id="new_form">
  <%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

        <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.text_area :name %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div id="new_o">
    <%= link_to 'Create a New Order!', new_order_path %>
</div>

app/views/orders/new.html.erb
<div id="new_form_header">
	<!-- this is what we'll be seeing -->
	<h1>New order</h1>

	<%= render 'form' %>

	<%= link_to 'Import Items', 'items' %>

</div>

app/views/orders/show.html.erb
<div id="show_form">
	<p id="notice"><%= notice %></p>
	<br>
	<br>
	<br>
	<p id="order">
	  <strong>Restaurant ID:</strong>
	  <!-- This will give us the restaurant id -->
	  <%= Order.search(@order.name)[0] %> 
	</p>
	<br>
	<br>
	<br>
	<p id="order">
	  <strong>Price:</strong>
	  <!-- this will give us the total price -->
	  <%= Order.search(@order.name)[1] %>
	</p>
	<br>
	<br>
	<br>
	<%= link_to 'Back', orders_path %>
</div>